# Generated by Django 6.0.6 on 2026-06-19 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_full_flow_upgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='display_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills_text',
            field=models.TextField(blank=True, help_text='Comma-separated skills'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='experience',
            field=models.IntegerField(blank=True, help_text='Years of Experience', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='accounts.skill'),
        ),
    ]
