# Generated by Django 6.0.6 on 2026-06-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_custom_id_profile_display_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_slot',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
