# Generated by Django 6.0.6 on 2026-06-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_application_ai_reason_application_ai_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email_sent',
            field=models.TextField(blank=True),
        ),
    ]
